import os, json, time
from datetime import datetime


METHODOLOGY_PHASES = """
## PHASE 1: RECONNAISSANCE (WAHH Ch.3-4)
- Subdomain enumeration: passive (crt.sh, AlienVault, urlscan.io) + active (subfinder, amass)
- DNS resolution & HTTP probing
- Technology detection: whatweb, wafw00f, header analysis
- Content discovery: gobuster, ffuf, common paths

## PHASE 2: VULNERABILITY ANALYSIS (WAHH Ch.5-13)
### Information Disclosure
- robots.txt, sitemap.xml, .git/config, .env, backup.sql
- Stack traces, debug endpoints, cloud metadata
### Authentication & Session Management
- JWT attacks, session fixation, OAuth misconfig
- Password reset poisoning, login bypass
### Access Control (IDOR)
- Parameter tampering, mass assignment, path traversal
- Horizontal & vertical privilege escalation
### Injection
- SQLi, NoSQLi, Command Injection, SSTI, XXE, LFI
### XSS
- Stored > Reflected > DOM-based
### SSRF
- Cloud metadata, internal port scanning
### File Upload
- Extension bypass, polyglot, zip slip
### Business Logic
- Race conditions, integer overflow, OTP bypass

## PHASE 3: AUTOMATED SCANNING
- nuclei (CVE scanning)
- nikto (web server scanning)
- wpscan (WordPress enumeration)

## PHASE 4: EXPLOITATION DEEP DIVE
- Weak credential testing (hydra, cewl)
- API-specific: BOLA, BFLA, GraphQL batching
- Chaining: LOW + LOW = CRITICAL

## PHASE 5: REPORTING
- CVSS v3.1 scored findings with POC
- Remediation recommendations
"""

MINDSET_RULES = """
1. "Never trust the client-side." — WAHH Rule #1
2. "Map the application fully before attacking." — WAHH Rule #2
3. "Follow the user-supplied data." — Bug Hunting Rule #1
4. "Read the JavaScript!" — Bug Hunting Rule #2
5. "Think like a developer, then exploit their assumptions." — WAHH Rule #3
6. "If one doesn't work, try the opposite." — Bug Hunting Rule #3
7. "Every feature is an attack surface." — WAHH Rule #4
8. "Chain everything. Low + Low = Critical." — Bug Hunting Rule #4
9. "The easiest bug to find is the one you're looking for."
10. "Know when to automate and when to go manual."
"""

TOOLKIT_REF = """
| Category | Tools |
|----------|-------|
| Recon | subfinder, amass, httpx, dnsx, gau, waybackurls |
| Mapping | whatweb, wafw00f, Wappalyzer |
| Directory | gobuster, ffuf, dirsearch |
| Scanning | nuclei, nikto, wpscan, sqlmap |
| Web Manip | Burp Suite, Caido, ZAP |
| Crack | hashcat, john, hydra |
| Wordlists | rockyou.txt, seclists |
| Chaining | Custom scripts, Turbo Intruder |
"""

VALIDATION_CHECKLIST = """
Before reporting ANY bug, verify:
- [ ] Not in scope exclusion list
- [ ] Reproducible 3/3 times
- [ ] Not a false positive (test with negative control)
- [ ] Impact clearly demonstrable
- [ ] Screenshot / request captured
- [ ] No destructive side effects
- [ ] Minimal POC
- [ ] Remediation suggestion ready
"""


def generate_report(target, output_dir, results, summary):
    os.makedirs(f"{output_dir}/01-recon", exist_ok=True)
    os.makedirs(f"{output_dir}/02-mapping", exist_ok=True)
    os.makedirs(f"{output_dir}/03-attack", exist_ok=True)
    os.makedirs(f"{output_dir}/04-auth", exist_ok=True)
    os.makedirs(f"{output_dir}/05-postexp", exist_ok=True)
    os.makedirs(f"{output_dir}/report", exist_ok=True)

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    # Copy recon outputs into 01-recon
    _copy_results(output_dir, "01-recon", results)

    # Generate report.md
    report_md = f"""# WhiteCrow Bug Bounty Engagement Report

**Target:** `{target}`
**Date:** {now}
**Tool Version:** WhiteCrow v1.1.0
**Methodology:** The Web Application Hacker's Handbook + Real-World Bug Hunting

---

## Executive Summary

Target `{target}` was scanned using WhiteCrow's automated bug bounty pipeline.
- **Duration:** {summary.get('elapsed_seconds', 'N/A')}s
- **Subdomains Found:** {summary.get('subdomains_found', 0)}
- **Live Hosts:** {summary.get('live_hosts', 0)}
- **Vulnerabilities Detected:** {summary.get('vulnerabilities_found', 0)}
- **Tools Used:** {len(summary.get('tools_used', []))}
- **Tools Skipped:** {len(summary.get('tools_skipped', []))}

---

## Findings

### Reconnaissance Results

**Subdomains:** {summary.get('subdomains_found', 0)} discovered

**Live Hosts:** {summary.get('live_hosts', 0)} responding

**Vulnerabilities:** {summary.get('vulnerabilities_found', 0)} potential issues found

*See `01-recon/` for detailed per-tool output.*

---

## Methodology Phases

{METHODOLOGY_PHASES}

---

## Mindset Rules

{MINDSET_RULES}

---

## Tool Kit Reference

{TOOLKIT_REF}

---

## Validation Checklist

{VALIDATION_CHECKLIST}

---

## Raw Output

All tool outputs are saved in `01-recon/` and `03-attack/`.

---

*Report generated by WhiteCrow v1.1.0*
*Framework: The Web Application Hacker's Handbook, 2nd Ed. & Real-World Bug Hunting*
"""

    with open(f"{output_dir}/report/report.md", "w") as f:
        f.write(report_md)

    # Generate executive summary
    exec_summary = f"""# WhiteCrow — Executive Summary

## Target: {target}
## Date: {now}

### Overview
A reconnaissance and vulnerability assessment was performed on {target}.

### Key Metrics
| Metric | Value |
|--------|-------|
| Scan Duration | {summary.get('elapsed_seconds', 'N/A')}s |
| Subdomains Discovered | {summary.get('subdomains_found', 0)} |
| Live Services Found | {summary.get('live_hosts', 0)} |
| Potential Vulnerabilities | {summary.get('vulnerabilities_found', 0)} |

### Tools Used
{', '.join(summary.get('tools_used', ['None']))}

### Tools Skipped (not installed)
{', '.join(summary.get('tools_skipped', ['None']))}

### Output Location
`{output_dir}/`

### Disclaimer
This assessment was performed for **educational purposes only**.
The developer is NOT responsible for any misuse.
"""
    with open(f"{output_dir}/report/executive_summary.md", "w") as f:
        f.write(exec_summary)

    # Save findings in structured format
    findings = {
        "target": target,
        "timestamp": now,
        "subdomains": summary.get("subdomains_found", 0),
        "live_hosts": summary.get("live_hosts", 0),
        "vulnerabilities": summary.get("vulnerabilities_found", 0),
        "tools_used": summary.get("tools_used", []),
        "tools_skipped": summary.get("tools_skipped", []),
    }
    with open(f"{output_dir}/report/findings.json", "w") as f:
        json.dump(findings, f, indent=2)

    return f"{output_dir}/report/report.md"


def _copy_results(output_dir, phase_dir, results):
    phase_path = f"{output_dir}/{phase_dir}"
    for tool_name, data in results.items():
        if isinstance(data, dict) and data.get("results"):
            ext = ".txt" if isinstance(data["results"], list) else ".json"
            out = f"{phase_path}/{tool_name}{ext}"
            try:
                with open(out, "w") as f:
                    if isinstance(data["results"], list):
                        f.writelines(f"{r}\n" for r in data["results"])
                    else:
                        json.dump(data["results"], f, indent=2)
            except Exception:
                pass
